In [4]:
# Image manipulation : How images are actually represented in computer 
                    #- How images actually work 
                    #- copy one part of image to another part of the image 

# VALUES THAT RERESENT OUR PIXELS
import cv2
img = cv2.imread('assets/logo.jpg',-1)
print(img) # A lot of matrices

print(type(img)) # <class 'numpy.ndarray'>
# Numpy : is a high performance library also used for arrays , allows to do most optimized operations with arrays

print(img.shape)  # (540, 960, 3) , no of rows[hight of image] ,no of cols[width of image] , no of channels in my image 3:(RGB)
# open cv used BGR
# standar is RGB 


# [0,0,0]: Read as blue,green,red

# an image of 2X2 pixels
# [
#     [[0,0,0],[255,255,255]],        # when ever we are manipulating an image : all we are doing is modiying this image
#     [[0,0,0],[255,255,255]]
# ] 

# These pixels are all set in cols , these cols are all in a row , you have multiple rows which have all column values in them , 
    #- inside of column you have your pixels  


# when we rotated image : it rotated the value of this matrix  
# NOTE : you can modify the image by modify the matrix that represent this image . 


[[[107 140 113]
  [107 140 113]
  [106 142 112]
  ...
  [ 53  15  27]
  [ 53  15  27]
  [ 53  15  27]]

 [[108 141 114]
  [108 141 114]
  [107 143 113]
  ...
  [ 53  15  27]
  [ 53  15  27]
  [ 53  15  27]]

 [[109 142 115]
  [110 143 116]
  [108 143 116]
  ...
  [ 53  15  27]
  [ 53  15  27]
  [ 53  15  27]]

 ...

 [[ 80  36  37]
  [ 79  35  36]
  [ 76  32  31]
  ...
  [ 53  16  26]
  [ 53  16  26]
  [ 53  16  26]]

 [[ 83  39  38]
  [ 81  37  36]
  [ 76  32  31]
  ...
  [ 53  16  26]
  [ 53  16  26]
  [ 53  16  26]]

 [[ 77  33  32]
  [ 77  33  32]
  [ 73  29  28]
  ...
  [ 53  16  26]
  [ 53  16  26]
  [ 53  16  26]]]
<class 'numpy.ndarray'>
(540, 960, 3)


In [10]:
# ACCESSING  PIXEL VALUES
#  lets look at the first row of our image
import cv2
img = cv2.imread('assets/logo.jpg')
# print(img[257][45:400]) # pixels between 45 and 400 in the first row 
print(img[257][400])


[95 60 56]


In [13]:
# CHANGING PIXEL COLOR  : RANDOMLY 
import cv2
import random 
img = cv2.imread('assets/logo.jpg',-1)

for i in range(100):
    for j in range(img.shape[1]): # imge.shape at index 1 , recall (rows,cols,shape)
        img[i][i]=[random.randint(0,255),random.randint(0,255),random.randint(0,255)]

cv2.imshow('Image',img) 
cv2.waitKey(0) # wait infinite amount of time 
cv2.destroyAllWindows()

In [13]:
# COPY ONE PART OF THE IMAGE AND PASTE IT TO ANOTHER PART OF THE IMAGE 

import cv2
import random 
img = cv2.imread('assets/logo.jpg',-1)

tag = img[500:700,600:900] # copy from  rows . 500 to 700(not including 700) , all the cols 600,900 (not including 900)

# we will paste our image  
img[0:200,250:550]=tag

cv2.imshow('Image',img) 
cv2.waitKey(0) # wait infinite amount of time 
cv2.destroyAllWindows()

ValueError: could not broadcast input array from shape (40,300,3) into shape (200,300,3)